# Official docker image.
image: node:10

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - yarn install
    - yarn coverage
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'

pages:
  stage: deploy
  script:
    - yarn install
    - yarn build
    - mv demo/dist public
  artifacts:
    paths:
      - public
  only:
    - master
